language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install Django==4.2.5

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test