language: python
python:
  - "3.8"

before_install:
  - pip install --upgrade pip>23.2

install:
  - pip install -r requirements.txt
  

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls --repo-token $COVERALLS_REPO_TOKEN