language: python
python:
  - "3.8"

before_install:
  - pip install --upgrade pip>23.2
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz


install:
  - pip install -r requirements.txt
  
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test
  - coverage xml -o coverage.xml

after_script:
  - coveralls --xml coverage.xml

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "mysite"
  env: "diango-env"
  bucket_name: "elasticbeanstalk-us-east-1-420169502545"
  on:
    branch: main