language: python
python:
  - "3.9"

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/backports
  - sudo apt-get update
  - sudo apt-get install -y sqlite3


install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test