language: python
dist: bionic
os: linux
python:
  - "3.10"

before_install:
  - pip install --upgrade pip>23.2

install:
  - pip install -r requirements.txt
  
script:
  - python manage.py test
  - python -m black --check .
  - python -m flake8 .
  - python -m coverage run manage.py test
  
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "mysite"
  env: "diango-env"
  bucket_name: "elasticbeanstalk-us-east-1-420169502545"
  on:
    branch: main