language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt
  

script:
  - python -m unittest discover
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test