language: python
python:
  - "3.8"

before_install:
  - pip install --upgrade pip>23.2

install:
  - pip install -r requirements.txt
  - pip install coverage-lcov
  
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test
  - coverage-lcov lcov.info
  
after_script:
  - npx coverallsuniversalreporter -l lcov -f ./lcov.info -n

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "mysite"
  env: "diango-env"
  bucket_name: "elasticbeanstalk-us-east-1-420169502545"
  on:
    branch: main